
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team02-s23-6pm-4
owner: ucsb-cs156-s23
repo_name: team02-s23-6pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjcwMTEzOTg3","is_bot":false,"login":"jessica-lieu","name":""},"headRefName":"JessicaL-PaintingsController","number":108,"title":"added PaintingController","url":"https://github.com/ucsb-cs156-s23/team02-s23-6pm-4/pull/108"},{"author":{"id":"MDQ6VXNlcjc3NjkzMzkz","is_bot":false,"login":"ykeung","name":"Yuki Keung"},"headRefName":"YukiK-BookController","number":107,"title":"yk - created book controller","url":"https://github.com/ucsb-cs156-s23/team02-s23-6pm-4/pull/107"}]
