
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team02-s23-6pm-4
owner: ucsb-cs156-s23
repo_name: team02-s23-6pm-4
pull_requests: [{"author":{"id":"U_kgDOB7ycjA","is_bot":false,"login":"JacobWoodward2000","name":"Jacob W"},"headRefName":"JacobW-ApartmentDatabase","number":104,"title":"jw-Add Apartment Database","url":"https://github.com/ucsb-cs156-s23/team02-s23-6pm-4/pull/104"},{"author":{"id":"MDQ6VXNlcjgxMzQxODE5","is_bot":false,"login":"kshitij0407","name":"Kshitij Agarwal"},"headRefName":"KrishA-table","number":103,"title":"added entity and repository- krish","url":"https://github.com/ucsb-cs156-s23/team02-s23-6pm-4/pull/103"},{"author":{"id":"MDQ6VXNlcjcwMTEzOTg3","is_bot":false,"login":"jessica-lieu","name":""},"headRefName":"JessicaL-PaintingsTable","number":102,"title":"jl - created database table for Paintings","url":"https://github.com/ucsb-cs156-s23/team02-s23-6pm-4/pull/102"},{"author":{"id":"MDQ6VXNlcjc3NjkzMzkz","is_bot":false,"login":"ykeung","name":"Yuki Keung"},"headRefName":"YukiK-BookDatabaseTable","number":101,"title":"yk - created book database table","url":"https://github.com/ucsb-cs156-s23/team02-s23-6pm-4/pull/101"}]
